### ISSUE TITLE
Logger Migration to Pino

### ISSUE THREAD

**Issue by UlisesGascon** [OpenPathfinder/visionBoard#132]
Currently, we use a [custom logger](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/1b618881f59d1831f1a2e602e974a8762adc6ae1/src/utils/index.js#L19) with limited capabilities.

The idea is to migrate to [Pino](https://github.com/pinojs/pino) with two key features:

1. **Prevent Leaks of Sensitive Data**  
   Sensitive data like `GITHUB_TOKEN` might inadvertently leak when passing environment variables to containers, especially if the containers fail to execute commands. For example ([Relevant Code](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/1b618881f59d1831f1a2e602e974a8762adc6ae1/src/providers/index.js#L66)): 
	```
	Error running workflow: Command failed: docker run -e GITHUB_AUTH_TOKEN=ghp_************************ --rm ghcr.io/ossf/scorecard/v5:ea7e27ed41b76ab879c862fa0ca4cc9c61764ee4 --repo=https://github.com/jshttp/content-type --show-details --format=json
	Error: check runtime error: CII-Best-Practices: internal error: error during json parsing: error during json.Unmarshal: invalid character '<' looking for beginning of value
		    2024/12/12 19:23:27 error during command execution: check runtime error: CII-Best-Practices: internal error: error during json parsing: error during json.Unmarshal: invalid character '<' looking for beginning of value
	```
	Using Pino, we can ensure sensitive data is redacted from logs to prevent such leaks ([ref1](https://lepape.me/nodejs-best-practices-redacting-secrets-from-pino-logs/), [ref2](https://github.com/pinojs/pino/blob/main/docs/redaction.md)).

2. **Suppress Logs During Test Execution**  
To maintain clean logs and simplify debugging, we aim to avoid logging when tests are running ([Relevant Code](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/1b618881f59d1831f1a2e602e974a8762adc6ae1/src/utils/index.js#L12))

**Comment by bjohansebas** [comment]
i can help with this ;)

**Comment by UlisesGascon** [comment]
Awesome! I will assign the issue to you. Let me know if you need help :)
