### ISSUE TITLE
Refactor the Store

### ISSUE THREAD

**Issue by UlisesGascon** [OpenPathfinder/visionBoard#135]
Currently, there’s plenty of room to improve [the store](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/1b618881f59d1831f1a2e602e974a8762adc6ae1/src/store/index.js). 

Ideally, we can abstract a bit more the functions and avoid code repetition for things like `getOne`, `getAll`, `upsert`, etc.

**Comment by telekosmos** [comment]
I can pick this one and give it a go

**Comment by UlisesGascon** [comment]
Welcome aboard @telekosmos! I will assign this issue to you, please let me know if you need help :)

**Comment by telekosmos** [comment]
Also, there are functions like these ones in `store` in `__utils__` folder with pretty much same functionality, they appear only  to be used in tests. It doesn't seem overcomplicated to remove those functions to avoid mismatching and duplicated code. It implies slight changes on tests and/or functions. Happy to listen comments or talk to figure out whether or not is worth to address.
