### ISSUE TITLE
Review the database schema

### ISSUE THREAD

**Issue by UlisesGascon** [OpenPathfinder/visionBoard#139]
It seems like the relations between the tables might have room for improvement. We want to make sure that relation fields like `github_organization.project_id` are not NULLABLE. 

Additionally, we should review the datatypes for the columns to ensure they are aligned with the content.

**Comment by bjohansebas** [comment]
i can help with this 😄

**Comment by UlisesGascon** [comment]
I assigned this issue to you, let me know if you need help :)

**Comment by bjohansebas** [comment]
We want to ensure that the IDs are numbers, or we could switch them to UUIDs?

**Comment by bjohansebas** [comment]
Here I will write about the changes:

- github_organizations: None, all match their type in the API.

**Comment by bjohansebas** [comment]
According to my review, only one change to the schema would be needed. I can't do it myself until next year, maybe someone else would like to do it.

**Comment by telekosmos** [comment]
> According to my review, only one change to the schema would be needed. I can't do it myself until next year, maybe someone else would like to do it.

For what I've seen and without knowing some aspects of the schema, _agree_ 👍 , `NOT NULL` constraints didn't seem to be that bad.

**Comment by UlisesGascon** [comment]
I think that with the changes in #160 and #167 we are good to go and we can close this issue, but we can re-open it again if we need more work on this again.
