### ISSUE TITLE
Identify solo-maintainer projects

### ISSUE THREAD

**Issue by UlisesGascon** [OpenPathfinder/visionBoard#146]
We need to a column `is_solo_maintainer_project` as boolean (default `false`) in the table `projects` as we need to identify projects that solo maintainer (by definition).

Certain checks require this filter: #76, #79, #107, #125 and #127

Note that just listing GitHub organization owners won't solve this as most of this projects have granted admin access level to the foundation or others in case that an emergency access is needed.

**Comment by bjohansebas** [comment]
I have been thinking about this problem to achieve automation, considering that access has been granted to the foundation. The possible options would be:

- Ignoring the foundation's accounts (I don't think this is the best option) with a blacklist.  
- Verifying who among those with write permissions has recently made a commit to the main repository (possibly the best option).  
- Doing this step manually.  

Or maybe there are better options.

**Comment by UlisesGascon** [comment]
> Doing this step manually. 

I think this is the way to go, when we add a project we can specify if the project is a solo-maintainer one. By default we consider the project to have a team based governance model.

Using the activity seems complex and requires pulling a lot of data when doing the project registration. Currently we don't use providers when adding a project.

**Comment by KoolTheba** [comment]
Hi @UlisesGascon 
I'd like to work on this issue.
Thanks! :-)

**Comment by UlisesGascon** [comment]
I assigned the issue to you. Thanks for the help @KoolTheba!

**Comment by UlisesGascon** [comment]
As we are using now checklist, this differentiation won't be necessary.
